services:
  coffee-house-service:
    # image: docker.io/jiflabs/coffee-house:latest

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "8080"
      DATA: "/data"
      CACHE: "/cache"
      USERNAME: "root"
      PASSWORD: "root"
      TRANSCODING: "true"

    volumes:
      - coffee-house-data:/app
      - coffee-house-cache:/cache
      - /home/felix/remote:/data:ro

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  coffee-house-data:
  coffee-house-cache:
